site_name: RikedyBlog
theme:
    name: material
    palette:
        primary: teal
        accent: pink 
    features:
        - navigation.tabs
    custom_dir: overrides
markdown_extensions:
    - pymdownx.highlight
    - pymdownx.superfences 
extra_css:
    - stylesheets/extra.css
plugins:
    - awesome-pages
