site_name: RikedyBlog
theme:
    name: material
    palette:
        primary: teal
        accent: pink 
    custom_dir: overrides
markdown_extensions:
    - pymdownx.highlight
    - pymdownx.superfences 
extra_css:
    - stylesheets/extra.css
plugins:
    - awesome-pages
    - search:
        lang: ja
    - tags:
        tags_file: tags.md
