site_name: RikedyBlog
theme:
    name: material
    palette:
        primary: teal
        accent: pink 
    custom_dir: overrides
    features:
        - navigation.tabs
markdown_extensions:
    - pymdownx.highlight
    - pymdownx.superfences 
extra_css:
    - stylesheets/extra.css
plugins:
    - awesome-pages
    - search:
        lang: ja
    - tags:
        tags_file: tags.md
nav:
  - Home: index.md
  - About: about.md
  - Tags: tags.md
  - History:
    - 2022: history/2022.md
    - 2021: history/2021.md